apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: dev
spec:
  replicas: 1  # Can increase if needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: betrand1997/my-static-websites:latest
          ports:
            - containerPort: 80    # The app runs on port 80 inside the container
              hostPort: 8080       # Expose directly on the VM's port 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            privileged: true  # Needed for `hostPort` in some Kubernetes setups
