apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: dev
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 50        # Port exposed by the service
      targetPort: 50  # Port your app listens to in the container
  type: NodePort