apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: dev  # or 'prod' depending on your environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: betrand1997/my-static-websites:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: my-app-secret
