apiVersion: v1
kind: Service
metadata:
  name: pod-a-service
  namespace: dev
spec:
  selector:
    workload.user.cattle.io/workloadselector: pod-dev-pod-a
  ports:
    - protocol: TCP
      port: 8080      # External port to access
      targetPort: 80  # The port the container listens on
  type: NodePort
