apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: dev
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080  # External port (maps to 80 inside the container)
      targetPort: 80  # The container's exposed port
  type: NodePort  # Change to NodePort if LoadBalancer isn't available