---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-admin
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: dashboard-admin
    namespace: dev  # ✅ Corrected namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-admin-token
  namespace: dev
  annotations:
    kubernetes.io/service-account.name: dashboard-admin
type: kubernetes.io/service-account-token
