name: Build and Push Python Package

on:
  push:
    branches:
      - main  
jobs:
  build:
    name: Build Python Package
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python Environment
        run: |
          python3 -m venv venv
          venv/bin/python -m pip install --upgrade pip
          venv/bin/pip install -r requirements.txt --no-cache-dir

      - name: Ensure Clean Build
        run: |
          rm -rf dist build *.egg-info

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Build Python Package
        run: |
          venv/bin/python -m pip install --upgrade setuptools wheel
          venv/bin/python setup.py sdist bdist_wheel
          ls -lah dist/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-${{ github.run_id }}
          path: dist/
