name: Build, Test, and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the 'main' branch
  
jobs:
  test:
    runs-on: self-hosted
    
    steps:
      - name: Install dependencies
        run:  yum install -y python3 python3-pip  # Use yum instead of apk

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          python3 -m ensurepip
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest -v


  