name: Build, Test, and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    container:
      image: alpine:latest 

    steps:
      - name: Install dependencies
        run: |
          yum install -y python3 python3-pip  # Use yum for Amazon Linux

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Betrand1999/project-root
          path: project-root  # Clones repo into _work/project-root/

      - name: Verify repository contents
        run: ls -lah project-root  # Debugging step

      - name: Install Python dependencies
        run: |
          cd project-root  # Navigate into project directory
          python3 -m ensurepip
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
        shell: bash

      - name: Run unit tests
        run: |
          cd project-root  # Navigate into project directory
          pytest -v tests/  # Ensure 'tests/' is the correct path for your test files
        shell: bash
