name: Secret Scan

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # optional: 0 for full commit history

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          # The v7.x CLI supports '--report=FILE' for JSON output
          args: "--repo-path=. --verbose --redact --commit-history --report=gitleaks-report.json"
      
      - name: Print Gitleaks Report
        run: |
          echo "=== Gitleaks JSON Report ==="
          cat gitleaks-report.json


# The Action itself includes the Gitleaks binary.
# GitHub Actions pulls that environment automatically.