name: Secret Scan

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # Make this 0 if you want the full commit history for deeper scans
          fetch-depth: 0  

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: "--repo-path=. --verbose --redact --commit-history"

# The Action itself includes the Gitleaks binary.
# GitHub Actions pulls that environment automatically.