name: Install Node 22 (Amazon Linux style)

on:
  push:
    branches:
      - main
  workflow_dispatch: {} # still allow manual runs

jobs:
  install-node22:
    runs-on: [self-hosted, Linux, X64]
    container:
      image: public.ecr.aws/amazonlinux/amazonlinux:2023

    steps:
      - name: Prep (update & tools)
        run: |
          dnf -y update
          dnf -y install curl sudo

      - name: Install Node.js 22 (yum style)
        shell: bash
        run: |
          set -euo pipefail
          if ! yum list installed nodejs >/dev/null 2>&1; then
            echo "Package nodejs is not installed. Installing Node.js 22 first..."
            # Add NodeSource repo for Node.js 22
            curl -fsSL https://rpm.nodesource.com/setup_22.x | sudo -E bash -
            sudo yum install -y nodejs
            echo "Installed Node.js version: $(node -v)"
          else
            echo "Node.js already installed: $(node -v 2>/dev/null || echo 'unknown')"
          fi

      - name: Show versions
        run: |
          node -v
          npm -v
