name: Install Node.js 22 and Serverless Framework

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  install-node22-serverless:
    runs-on: [self-hosted, Linux, X64]
    container:
      image: public.ecr.aws/amazonlinux/amazonlinux:2023

    steps:
      - name: Install Node.js 22 and Serverless
        shell: bash
        run: |
          set -euo pipefail
          
          if ! command -v sls &>/dev/null; then
            if ! yum list installed nodejs >/dev/null 2>&1; then
              echo "Package nodejs is not installed. Installing Node.js 22 first..."
              # Add NodeSource repo for Node.js 22
              curl -fsSL https://rpm.nodesource.com/setup_22.x | bash -
              # Install Node.js (will be v22 from NodeSource)
              yum install -y nodejs
              echo "Installed Node.js version: $(node -v)"
            fi
            echo "Installing Serverless framework..."
            npm install -g serverless@2.72.3
            echo "Installed Serverless version: $(sls -v)"
          else
            echo "Serverless framework is already installed. Skipping..."
            sls -v
          fi

      - name: Show versions
        run: |
          node -v
          npm -v
          sls -v

