name: Build & Deploy with Kpack

on:
  push:
    branches:
      - main
      - new_feature_branch

jobs:
  package-and-publish:
    name: Publish to PyPI
    runs-on: macos-latest
    needs: sonarqube
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name your-cluster-name

      - name: Run kpack
        run: |
          kubectl apply -f ${{ github.workspace }}/kpack/namespace.yaml
          kubectl apply -f ${{ github.workspace }}/kpack/build-image.yaml
          kubectl apply -f ${{ github.workspace }}/kpack/run-image.yaml
