name: Deploy with Pack Build

on:
  push:
    branches:
      - main
      - new_feature_branch

jobs:
  pack-build:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Disable Docker Keychain Helper
        run: |
          mkdir -p ~/.docker
          echo '{ "credsStore": "" }' > ~/.docker/config.json

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Image with Pack
        run: |
          pack build docker.io/betrand1997/my-app \
            --builder heroku/builder:24 \
            --path . \
            --publish \
            --tag docker.io/betrand1997/my-app:latest
