name: Deploy to Kubernetes via SSH

on:
  push:
    branches:
      - main  # or your working branch

jobs:
  deploy:
    name: Deploy to Kubernetes on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug - List current directory
        run: ls -la

      - name: Debug - List kubernetes folder
        run: ls -la kubernetes

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Kubernetes Manifests to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./kubernetes ec2-user@3.208.1.75:/home/ec2-user/

      - name: Apply Kubernetes Manifests on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.208.1.75 << 'EOF'
            kubectl apply -f /home/ec2-user/kubernetes/dev-namespace.yaml -n dev
            kubectl apply -f /home/ec2-user/kubernetes/dev-deployment.yaml -n dev
            kubectl apply -f /home/ec2-user/kubernetes/dev-service.yaml -n dev
            kubectl rollout status deployment/my-app -n dev
          EOF
